# planet.js configuration

planet:
  name: Planet Example # Site title
  tagline: Here's your tagline under title # Site tagline
  description: Yet another planet site # Site description
  link: https://planet.example.com # Site link, do NOT include tailing slash '/'
  locale: en # Site locale
  owner_name: Joe Doe # Your name
  owner_email: joe@example.com # Your email
  theme: pure # theme under templates directory
  output: public # output directory, make sure your web server can read in this place
  timeout: 30 # request timeout in seconds
  items: 100 # how many posts should be displayed?
  items_feed: 200 # maximum posts in feed
  display_length: 2000 # posts longer than this characters, a summary will be displayed (if available)
  post_update: false # use post update time in feeds. If enabled, post update date will be used to sort in list
  time_format: MMMM Do YYYY h:mm:ss A # See http://momentjs.com/docs/#/displaying/ for details
  ttl: 120 # TimeToLive minutes to cache site feed
  lazyload: false # Use Lazyload for image

secure:
  proxy: # Leave blank if you don't use an http proxy
  allowedTags: # set to true to allow any tags, or [] to disallow any.
  - h1
  - h2
  - h3
  - h4
  - h5
  - h6
  - blockquote
  - p
  - a
  - ul
  - ol
  - nl
  - li
  - b
  - i
  - s
  - g
  - strong
  - em
  - strike
  - del
  - pre
  - code
  - kbd
  - hr
  - br
  - div
  - table
  - thead
  - tbody
  - tr
  - th
  - td
  - caption
  - img
  - sup
  - sub
  - span
  - font
  - svg
  - defs
  - path
  - use
  allowedAttributes:
    a:
    - href
    - name
    - target
    - 'data-*'
    img:
    - src
    - title
    - alt
    - 'data-*'
  selfClosing:
  - img
  - br
  - hr
  allowedSchemes:
  - http
  - https
  - ftp
  - mailto
  - data
  allowProtocolRelative: true

people:
- name: Example Google News Feed
  link: https://news.google.com/news?output=rss
  avatar: images/akarin.jpg # available types: file path, gravatar email, http(s) image uri, or just leave blank
